# Setup
title: Tar
description: Tar Pages
paginate: 1

# defaults
defaults:
  -
    scope:
      path: "_posts" # 이 빈 문자열은 프로젝트 내의 모든 파일을 의미한다
    values:
      layout: "post"
      
      

# Gems
gems:
  - jekyll-paginate
