# Setup
title: Tar
description: Tar Pages
paginate: 1


# defaults
defaults:
  -
    scope:
      path: "_posts" # 적용할 폴더를 입력
    values:
      layout: "post" # layout의 기본값을 post로 지정
      author: "Tar Kim"
      
      
# Gems
gems:
  - jekyll-paginate # 페이지네이션을 위한 gem
