# Setup
title: Tar Kim
description: Travel Around The World

# defaults
defaults:
  - scope:
      path: "_posts" # 적용 할 폴더 지정
    values:
      # layout: "post" # layout 기본값을 post로 지정
      layouts_dir: baseurl
      # layout 폴더 경로를 루트로 
      author: "Tar Kim"
      permalink: /:title/ # permalink 형식 지정
      
# paginate
paginate: 1
paginate_path: /list:num/
gems:
  - jekyll-paginate
