# Setup
title: Tar
description: Tar Pages

# defaults
defaults:
  - scope:
      path: "_posts" # 적용 할 폴더 지정
    values:
      layout: "post" # layout 기본값을 post로 지정
      author: "Tar Kim"
      permalink: /:title # permalink 형식 지정
      
# paginate
paginate: 1
paginate_path: /:num/
gems:
  - jekyll-paginate
